packages:
  - "apps/*"
  - "packages/*"
  - "plugins/*"
minimumReleaseAge: 10080
trustPolicy: no-downgrade
blockExoticSubdeps: true
trustPolicyExclude:
  - "vite@5.4.21"

allowBuilds:
  esbuild: true
